Repository bitmakerla/estela, pull requests merged in 2022-12, with the labels that each got.

#97 BITMAKER-2079 estela-web: Implement new "SpiderPage"
  estela-web/src/components/SpiderListPage/index.tsx
  estela-web/tailwind.config.js
Labels: enhancement

#112 BITMAKER-2199 estela-web: Implement "Spider/Overview" mockup
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/src/components/SpiderDetailPage/styles.scss
  estela-web/webpack.config.js
Labels: enhancement

#113 BITMAKER-2209 estela-web: Connect Resources Consumption in Dashboard component
  estela-web/package.json
  estela-web/src/components/ProjectDashboardPage/index.tsx
  estela-web/src/components/ProjectDashboardPage/styles.scss
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/yarn.lock
Labels: bug

#116 Bitmaker 2101 estela-web: Implement "Jobs/Overview" mockup
  estela-web/src/components/JobDetailPage/index.tsx
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/tailwind.config.js
Labels: enhancement

#108 BITMAKER-2162 Solve estela-web warnings & reformat components code
  estela-web/package.json
  estela-web/src/components/CronJobDetailPage/index.tsx
  estela-web/src/components/DeployListPage/index.tsx
  estela-web/src/components/JobDetailPage/index.tsx
  estela-web/src/components/NotificationsInboxPage/index.tsx
  estela-web/src/components/NotificationsSettingsPage/index.tsx
  estela-web/src/components/ProjectCronJobListPage/index.tsx
  estela-web/src/components/ProjectDashboardPage/index.tsx
  estela-web/src/components/ProjectJobListPage/index.tsx
  estela-web/src/components/ProjectListPage/index.tsx
  estela-web/src/components/ProjectMemberPage/index.tsx
  estela-web/src/components/ProjectSettingsPage/index.tsx
  estela-web/src/components/SettingsDataPersistencePage/index.tsx
  estela-web/src/components/SettingsPasswordPage/index.tsx
  estela-web/src/components/SettingsProfilePage/index.tsx
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/src/components/SpiderListPage/index.tsx
  estela-web/src/services/auth.service.ts
  estela-web/src/shared/header/index.tsx
  estela-web/src/shared/notificationsList/index.tsx
  estela-web/src/shared/notificationsSidenav/index.tsx
  estela-web/src/shared/profileSettingsSidenav/index.tsx
  estela-web/src/shared/projectSidenav/index.tsx
  estela-web/src/shared/projectSidenav/styles.scss
  estela-web/yarn.lock
Labels: enhancement

#120 BITMAKER-2267 estela-web: Error displaying data collected from "Jobs/Overview"
  estela-web/src/assets/icons/export.svg
  estela-web/src/components/JobDetailPage/index.tsx
  estela-web/src/components/JobDetailPage/styles.scss
Labels: enhancement

#122 BITMAKER-2277 estela-api: Query parameters are not received on Usage endpoint in estela api
  estela-api/api/views/project.py
Labels: invalid

#119 BITMAKER-2225 estela-web: Implement "InProject/Jobs" mockup
  estela-api/api/serializers/job.py
  estela-api/api/views/job.py
  estela-api/docs/api.yaml
  estela-web/src/components/JobDetailPage/index.tsx
  estela-web/src/components/ProjectCronJobListPage/index.tsx
  estela-web/src/components/ProjectJobListPage/index.tsx
  estela-web/src/components/ProjectJobListPage/styles.scss
  estela-web/src/services/api/generated-api/models/SpiderJobCreate.ts
  estela-web/tailwind.config.js
Labels: enhancement
