Repository bitmakerla/estela, pull requests merged in 2022-11, with the labels that each got.

#95 BITMAKER-2100 estela-web: Implement "In Projects/Scheduled Jobs"
  estela-api/api/views/cronjob.py
  estela-web/src/components/ProjectCronJobListPage/index.tsx
  estela-web/src/components/ProjectCronJobListPage/styles.scss
  estela-web/src/components/ProjectListPage/index.tsx
  estela-web/src/components/ProjectMemberPage/index.tsx
  estela-web/src/components/ProjectSettingsPage/index.tsx
  estela-web/tailwind.config.js
Labels: enhancement

#101 BITMAKER-2132 Get Role in Project List request
  estela-web/src/components/ProjectListPage/index.tsx
Labels: bug, enhancement

#104 BITMAKER-2143 Delete specific warnings alerts logs on browser
  estela-web/src/components/ProjectCronJobListPage/index.tsx
Labels: bug

#105 BITMAKER-2155 estela-documentation: Add information to enhance installation experience
  docs/FAQ/index.md
  docs/estela-cli/quickstart.md
  docs/estela/installation/helm-variables.md
  docs/estela/installation/main-guide.md
  docs/estela/installation/resources.md
  installation/Makefile
Labels: documentation, enhancement

#107 Bitmaker 2163 estela-web: Implement "Spider/Settings" mockup
  estela-web/src/assets/icons/play.svg
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/src/components/SpiderDetailPage/styles.scss
Labels: enhancement

#103 BITMAKER-2148 estela-api: Delete Cronjob request && Delete Member and change MemberRole
  estela-api/api/serializers/cronjob.py
  estela-api/api/serializers/project.py
  estela-api/api/views/cronjob.py
  estela-api/api/views/project.py
  estela-api/core/migrations/0021_spidercronjob_deleted.py
  estela-api/core/models.py
  estela-api/docs/api.yaml
  estela-web/src/components/ProjectCronJobListPage/index.tsx
  estela-web/src/components/ProjectCronJobListPage/styles.scss
  estela-web/src/components/ProjectMemberPage/index.tsx
  estela-web/src/components/ProjectMemberPage/styles.scss
  estela-web/src/services/api/generated-api/apis/ApiApi.ts
  estela-web/src/services/api/generated-api/models/ProjectUpdate.ts
  estela-web/src/shared/projectSidenav/index.tsx
Labels: enhancement

#106 BITMAKER-2142 estela-web: Implement "In Projects/Scheduled Jobs"
  estela-web/package.json
  estela-web/src/assets/icons/edit.svg
  estela-web/src/assets/icons/filter.svg
  estela-web/src/assets/icons/pause.svg
  estela-web/src/assets/icons/play.svg
  estela-web/src/components/CronJobDetailPage/index.tsx
  estela-web/src/components/CronJobDetailPage/styles.scss
  estela-web/src/components/ProjectCronJobListPage/index.tsx
  estela-web/yarn.lock
Labels: enhancement
