Repository bitmakerla/estela, pull requests merged in 2023-01, with the labels that each got.

#124 BITMAKER-2266 estela-web: Fix display "Jobs/Overview" mockup
  estela-web/package.json
  estela-web/src/components/JobDetailPage/index.tsx
  estela-web/yarn.lock
Labels: invalid

#127 estela-cli: Add pip estela package to onboarding
  docs/estela-cli/install.md
Labels: documentation, enhancement

#131 BITMAKER-2323 estela-api: UsageRecord request doesn't show any record of usage
  estela-api/config/settings/local.py
  estela-api/config/settings/prod.py
  estela-api/core/signals.py
Labels: help wanted

#135 BITMAKER-2338 estela-api: Create OwnerProject Role on user permissions
  estela-api/api/permissions.py
  estela-api/api/views/project.py
  estela-api/core/migrations/0022_project_category.py
  estela-api/core/migrations/0023_auto_20230113_0354.py
  estela-api/core/models.py
  estela-api/docs/api.yaml
  estela-web/src/components/JobCreatePage/index.tsx
  estela-web/src/components/JobCreatePage/styles.scss
  estela-web/src/components/ProjectJobListPage/index.tsx
  estela-web/src/components/ProjectListPage/index.tsx
  estela-web/src/components/SpiderDetailPage/index.tsx
  estela-web/src/routes/index.tsx
  estela-web/src/services/api/generated-api/models/Permission.ts
Labels: enhancement, dependencies

#130 BITMAKER-1901: Allow setting RAM limits to SpiderJobs and SpiderCronJobs
  docs/estela/installation/helm-variables.md
  estela-api/api/serializers/cronjob.py
  estela-api/api/serializers/job.py
  estela-api/api/validators.py
  estela-api/api/views/cronjob.py
  estela-api/api/views/job.py
  estela-api/config/settings/base.py
  estela-api/core/cronjob.py
  estela-api/core/migrations/0024_spider_job_limits.py
  estela-api/core/models.py
  estela-api/core/tasks.py
  estela-api/engines/kubernetes.py
  estela-api/tests/core/test_kubernetes.py
  installation/helm-chart/values.yaml.example
Labels: enhancement

#136 BITMAKER-2322: BC-billing-web: Create checkout flow with prebuilt UI stripe components.
  estela-web/webpack.mf.config.js
Labels: enhancement

#138 BITMAKER-2274 estela-web: Issues with UsageRecord request
  estela-web/src/components/ProjectDashboardPage/index.tsx
Labels: bug

#140 BITMAKER-2375 estela-web: Fix estela logo
  estela-web/src/assets/logo/bitmaker.svg
  estela-web/src/components/LoginPage/index.tsx
  estela-web/src/components/RegisterPage/index.tsx
Labels: bug
